syntax = "proto2";

package utf8validation;

option java_package = "com.google.protobuf.utf8validation";
option java_outer_classname = "Utf8TestProto2UncheckedProto";
option java_multiple_files = true;
option java_string_check_utf8 = false;

message Utf8TestProto2Unchecked {
  optional string unchecked_unset = 1;

  // TODO: Enable once allowlist entry is built into protoc.
  // optional string unchecked_unenforced = 2 [enforce_utf8 = false];

  optional string unchecked_enforced = 3 [enforce_utf8 = true];

  extensions 100 to 200;
}

extend Utf8TestProto2Unchecked {
  optional string ext_unchecked_unset = 100;

  // TODO: Enable once allowlist entry is built into protoc.
  // optional string ext_unchecked_unenforced = 101 [enforce_utf8 = false];

  optional string ext_unchecked_enforced = 102 [enforce_utf8 = true];
}
